export default {
  elButton: [
    '<script setup lang="ts">',
    'const { t } = useI18n({',
    '  useScope: "local",',
    '})',
    '</script>',
    '',
    '<i18n lang="yaml">',
    'en:',
    '  button: Click me',
    'zh-CN:',
    '  button: 點擊我',
    'zh-TW:',
    '  button: 點擊我',
    '</i18n>',
    '',
    '<template>',
    '  <ElButton>{{ t("button") }}</ElButton>',
    '</template>',
  ].join('\n'),
  lazyElButton: [
    '<script setup lang="ts">',
    'const { t } = useI18n({',
    '  useScope: "local",',
    '})',
    '</script>',
    '',
    '<i18n lang="yaml">',
    'en:',
    '  button: Click me',
    'zh-CN:',
    '  button: 點擊我',
    'zh-TW:',
    '  button: 點擊我',
    '</i18n>',
    '',
    '<template>',
    '  <LazyElButton>{{ t("button") }}</LazyElButton>',
    '</template>',
  ].join('\n'),
}
